### ISSUE TITLE
Helpshift.isSupported returns false on iOS

### ISSUE THREAD

**Issue by jimmymjing** [airnativeextensions/ANE-Helpshift#1]
Hello,
`Helpshift.isSupported` returns `false` on my iPhone. I'm using debug provisioning profile. Should it work in this case?
FYI:
1. hs__data is packaged
2. When I added this ANE, Flash Builder shows that it is not support for iOS.

##### Environment 

- AIR SDK version: AIR 33.1.1.575
- Device OS: iOS 14
- Device version: iphone x
- Development IDE: flash builder 4.7
- Development OS: windows 7

**Comment by marchbold** [comment]
Hi,

This extension was a custom build for a client who was happy to release it. It only supports Android currently and is not covered by our support. Feel free to reach out to our custom development team if you need any functionality added to this extension.

Cheers

**Comment by jimmymjing** [comment]
Oh, thanks so much for making it clear! I read the wiki and thought it supports both Android and iOS.

**Comment by marchbold** [comment]
Yeah sorry, it's probably not clear, as I believe we initially had iOS on the plans but it got cancelled.
